# Site content in English and Korean. Edit here, then run: python _src/build.py
# To add a game: add an entry to GAMES (and its screenshots to screenshots.json).

STUDIO = {
    "name": "ggook's studio",
    "email": "admin@kysystemstudio.com",
    "youtube": "https://www.youtube.com/@ggooksstudio",
    "instagram": "https://www.instagram.com/ggooksstudio/",
    "domain": "https://kysystemstudio.com",
}

UI = {
    "en": {
        "lang_name": "English",
        "nav_games": "Games",
        "nav_news": "News",
        "nav_about": "About",
        "nav_support": "Support",
        "tagline": "Small, friendly mobile games",
        "hero_text": "We make simple games and learning apps you can enjoy in a minute and come back to every day.",
        "games_title": "Our games",
        "games_lead": "Free on Google Play.",
        "news_title": "News",
        "news_latest": "Latest news",
        "news_all": "All news",
        "get_play": "Get it on Google Play",
        "play_short": "Google Play",
        "screenshots": "Screenshots",
        "trailer": "Watch",
        "about_game": "About the game",
        "features": "Features",
        "game_links": "Help & policies",
        "privacy": "Privacy Policy",
        "support": "Support",
        "contact": "Contact",
        "more_games": "More games",
        "new": "NEW",
        "kind_game": "Game",
        "kind_learning": "Learning",
        "faq_title": "Frequently asked questions",
        "contact_title": "Contact us",
        "contact_text": "Questions, bug reports or ideas? Email us and we'll get back to you, usually within a few days.",
        "contact_tip": "For bug reports, please include the game name, your phone model and the app version (shown in the game's settings).",
        "about_title": "About us",
        "not_found_title": "Page not found",
        "not_found_text": "The page you're looking for doesn't exist.",
        "back_home": "Back to home",
        "rights": "All rights reserved.",
    },
    "ko": {
        "lang_name": "한국어",
        "nav_games": "게임",
        "nav_news": "소식",
        "nav_about": "소개",
        "nav_support": "지원",
        "tagline": "작고 친근한 모바일 게임",
        "hero_text": "잠깐 즐기고, 매일 다시 찾고 싶은 간단한 게임과 학습 앱을 만듭니다.",
        "games_title": "게임",
        "games_lead": "Google Play에서 무료로 즐기세요.",
        "news_title": "소식",
        "news_latest": "최근 소식",
        "news_all": "전체 소식",
        "get_play": "Google Play에서 받기",
        "play_short": "Google Play",
        "screenshots": "스크린샷",
        "trailer": "영상",
        "about_game": "게임 소개",
        "features": "특징",
        "game_links": "도움말 및 정책",
        "privacy": "개인정보처리방침",
        "support": "지원",
        "contact": "문의",
        "more_games": "다른 게임",
        "new": "NEW",
        "kind_game": "게임",
        "kind_learning": "학습",
        "faq_title": "자주 묻는 질문",
        "contact_title": "문의하기",
        "contact_text": "궁금한 점, 버그 제보, 아이디어가 있다면 이메일로 보내 주세요. 보통 며칠 안에 답장드립니다.",
        "contact_tip": "버그를 제보하실 때는 게임 이름, 휴대폰 기종, 앱 버전(게임 설정 화면에 표시)을 함께 적어 주세요.",
        "about_title": "스튜디오 소개",
        "not_found_title": "페이지를 찾을 수 없습니다",
        "not_found_text": "요청하신 페이지가 없습니다.",
        "back_home": "홈으로",
        "rights": "All rights reserved.",
    },
}

GAMES = [
    {
        "slug": "pass-or-splash",
        "package": "com.kysystemstudio.wallgame",
        "kind": "game",
        "new": True,
        "icon": "https://play-lh.googleusercontent.com/72gCmCGgDmlfmDwJfdx5CqhpENtnNpU-_r1uVHbD3UJmKMYLKQ9MmsBwFua-7t6ULdLOGmzOmglSmUN2nVpc9g",
        "shots_key": "wallgame",
        "youtube": None,
        "en": {
            "name": "Pass or Splash",
            "short": "Slide through the right hole before the wall hits. Wrong answer? Splash!",
            "body": [
                "A wall full of holes is rushing toward you. Read the puzzle at the top and slide your buddy in front of the right answer. Pick the wrong hole and the wall pushes you in: splash!",
                "Solve sums from addition to order of operations, find the biggest or smallest number, match shapes, count dots and follow the shuffling discs. Play 100 stages across five worlds, from the pool and the mud to cream, a ball pit and springs, each with its own silly penalty.",
            ],
            "features": ["Drag left and right with one finger", "No text to read: every rule is clear at a glance",
                         "Math, shape, counting and memory walls", "100 stages in 5 worlds", "About 40 seconds per stage"],
        },
        "ko": {
            "name": "Pass or Splash: 통과냐 풍덩이냐",
            "short": "벽이 닥치기 전에 정답 구멍으로! 틀리면 풍덩!",
            "body": [
                "구멍 뚫린 벽이 점점 다가옵니다. 화면 위 문제를 보고 정답이 적힌 구멍 앞으로 캐릭터를 옮기세요. 틀린 구멍을 고르면 벽에 밀려 풍덩!",
                "덧셈부터 복합 연산까지 계산 문제, 가장 큰 수와 작은 수 찾기, 같은 도형 찾기, 점 개수 세기, 섞이는 원판 따라가기까지 다양한 벽이 나옵니다. 물웅덩이, 진흙탕, 크림, 볼풀, 스프링으로 이어지는 5개 월드, 100개 스테이지에서 월드마다 웃긴 벌칙이 기다립니다.",
            ],
            "features": ["손가락 하나로 좌우 드래그", "읽을 필요 없이 한눈에 보이는 규칙", "계산, 도형, 개수, 기억력 벽",
                         "5개 월드, 100개 스테이지", "한 판 약 40초"],
        },
    },
    {
        "slug": "bust-below",
        "package": "com.kysystemstudio.bustbelow",
        "kind": "game",
        "new": True,
        "icon": "https://play-lh.googleusercontent.com/cunXHDmOAa_WUuArWOq4gl_Bhx4a2B2DvFXDTWlBt0UyAqruDFkqbYIJw3t8D3yKp9PqJi5Ii0VZTkWmbUfD5g",
        "shots_key": "bustbelow",
        "youtube": "9Hveia4oqBU",  # 16:9 trailer (the vertical Short is O5LQoBoKOjA)
        "video_wide": True,
        "en": {
            "name": "Bust Below: Idle Cop Tycoon",
            "short": "Send your cops into a crook-filled underground mall and watch the bounty roll in.",
            "body": [
                "A crime ring has taken over an abandoned underground mall. From a tiny police station in the corner, your cops head out on their own: they chase down crooks, cuff them and walk them back to the holding cell while the bounty rolls in.",
                "Clear three hideouts: an ice cream shop, a museum full of stolen goods and an underground casino. The deeper you go, the tougher the crooks and the bigger the bounty. Bosses take the whole squad to bring down, and they go straight to the prosecutors. Your cops keep working even while the game is closed.",
            ],
            "features": ["Cops that work on their own", "Three hideouts, each with a boss", "Promotions from Cadet to Captain",
                         "Station upgrades and material collectors", "Offline rewards, no forced ads"],
        },
        "ko": {
            "name": "Bust Below: Idle Cop Tycoon",
            "short": "지하 쇼핑몰에 숨은 범죄자들을 경찰들이 알아서 잡아 옵니다. 쌓이는 현상금을 모아 보세요.",
            "body": [
                "범죄 조직이 버려진 지하 쇼핑몰을 점령했습니다. 구석의 작은 경찰서에서 출동한 경찰들이 스스로 범죄자를 쫓아 체포하고 유치장으로 데려옵니다. 쌓이는 현상금을 지켜보세요.",
                "아이스크림 가게, 도난품으로 가득한 박물관, 지하 카지노까지 세 은신처를 소탕하세요. 깊이 들어갈수록 범죄자는 강해지고 현상금은 커집니다. 두목은 팀 전체가 힘을 모아야 잡을 수 있고, 잡으면 검찰로 넘깁니다. 게임을 꺼 두어도 경찰들은 계속 일합니다.",
            ],
            "features": ["알아서 일하는 경찰들", "두목이 있는 세 은신처", "신병부터 경감까지 승진",
                         "경찰서 시설 업그레이드와 수집가 고용", "오프라인 보상, 강제 광고 없음"],
        },
    },
    {
        "slug": "hilltop-roll",
        "package": "com.kysystemstudio.hilltoproll",
        "kind": "game",
        "new": True,
        "icon": "https://play-lh.googleusercontent.com/tGYEZyvIGvcaTSHyL7LfoSvJ6Z7WhSvP-YEazH95RkPSCKRptusGGlq3aTrZrOHR01ggYWuc9vkMWAH7uAsRENA",
        "shots_key": "hilltoproll",
        "youtube": "ppqi-XRWFIk",  # 16:9 trailer (the vertical Short is ayEe_S9SKBk)
        "video_wide": True,
        "en": {
            "name": "Hilltop Roll",
            "short": "Roll, steer and fly over the gaps. How far can you go?",
            "body": [
                "Hold to roll heavy and race down the hills. Let go to turn light and fly off the hilltops.",
                "Drag to steer through zigzag roads, tilted roads and forks. Hit the ramps to leap over the gaps, and land along the slope for a PERFECT boost. Every few seconds the road speeds up. How long can you keep rolling?",
            ],
            "features": ["One-finger controls", "Endless, ever-changing tracks", "Perfect landings and combo boosts",
                         "Calm pastel worlds that shift as you go", "Music and sound effects you can turn on or off"],
        },
        "ko": {
            "name": "Hilltop Roll",
            "short": "구르고, 조종하고, 틈을 넘어 날아오르세요. 얼마나 멀리 갈 수 있을까요?",
            "body": [
                "누르고 있으면 공이 무거워져 언덕을 빠르게 내려가고, 손을 떼면 가벼워져 언덕 꼭대기에서 날아오릅니다.",
                "드래그해서 지그재그 길, 기울어진 길, 갈림길을 헤쳐 나가세요. 점프대로 구멍을 뛰어넘고, 경사면을 따라 착지하면 PERFECT 부스트를 받습니다. 몇 초마다 길이 점점 빨라집니다. 얼마나 오래 굴러갈 수 있을까요?",
            ],
            "features": ["한 손가락으로 하는 간단한 조작", "끝없이 바뀌는 트랙", "PERFECT 착지와 콤보 부스트",
                         "달릴수록 바뀌는 차분한 파스텔 세상", "켜고 끌 수 있는 음악과 효과음"],
        },
    },
    {
        "slug": "updraft",
        "package": "com.kysystemstudio.paperplane",
        "kind": "game",
        "new": False,
        "icon": "https://play-lh.googleusercontent.com/khOGY-bR04FHAUyTEaxtXyn6bQNWoyhN6IVsPL1C8hTj00TSI8hC5brClVFr3-93mpnVz6OBQoFu6sNgoGMg",
        "shots_key": "paperplane",
        "youtube": "Sd4F3XZtObY",  # 16:9 trailer (the vertical Short is jwLs-Ii4w5E)
        "video_wide": True,
        "en": {
            "name": "Updraft: Paper Plane Launch",
            "short": "Aim, power up and launch your paper plane. Ride the updrafts and fly far!",
            "body": [
                "How far can one paper plane fly? Pick your angle, stop the power gauge at just the right moment, and let it go. Once your plane leaves your hand there is no steering: every flight is decided by your aim, your timing and the upgrades you've earned.",
                "Catch updrafts to climb higher, avoid downdrafts, and fly through five zones: the Park, the City, the Sea, the Mountains and Above the Clouds.",
            ],
            "features": ["Simple one-finger launch", "Updrafts, downdrafts, gusts and daily wind",
                         "Five zones full of obstacles", "Six upgrades and pre-launch skills",
                         "Daily rewards and missions"],
        },
        "ko": {
            "name": "Updraft: Paper Plane Launch",
            "short": "조준하고, 힘을 모아, 종이비행기를 날리세요. 상승기류를 타고 멀리!",
            "body": [
                "종이비행기 한 장은 얼마나 멀리 날 수 있을까요? 각도를 정하고, 힘 게이지를 딱 맞는 순간에 멈춘 뒤 날려 보세요. 손을 떠난 비행기는 조종할 수 없습니다. 조준, 타이밍, 그리고 모은 업그레이드가 비행을 결정합니다.",
                "상승기류를 타고 더 높이 오르고 하강기류는 피하며, 공원, 도시, 바다, 산, 구름 위까지 다섯 구역을 날아가세요.",
            ],
            "features": ["한 손가락으로 하는 간단한 발사", "상승기류, 하강기류, 돌풍, 오늘의 바람",
                         "장애물이 가득한 다섯 구역", "업그레이드 6종과 발사 전 스킬", "매일 출석 보상과 일일 미션"],
        },
    },
    {
        "slug": "korean-word-quiz",
        "package": "com.kysystemstudio.hangulchallenge",
        "kind": "learning",
        "new": False,
        "icon": "https://play-lh.googleusercontent.com/OPmno-V_8ryax5CUibl9EYw1V6tTqOw7YRNOIAB41WWqi5b8oY-Zr7z808zizjmb5DB-_4JcLFATxjZ5WclaJg",
        "shots_key": "hangulchallenge",
        "youtube": None,
        "en": {
            "name": "Korean Word Quiz",
            "short": "Build Korean vocabulary with 4,500 words. Nouns, verbs and adjectives.",
            "body": [
                "Whether you're just starting Korean or brushing up for travel, TOPIK or daily conversation, Korean Word Quiz turns vocabulary practice into a quick, satisfying daily habit.",
                "Practice 1,500 nouns, 1,500 verbs and 1,500 adjectives in short 10-question sessions, with native pronunciation and automatic review of the words you missed.",
            ],
            "features": ["4,500 essential words", "Korean to English and English to Korean questions",
                         "Native pronunciation (text-to-speech)", "Review your wrong answers and learned words",
                         "No account needed, works offline"],
        },
        "ko": {
            "name": "Korean Word Quiz",
            "short": "필수 한국어 단어 4,500개로 어휘력을 키우세요. 명사, 동사, 형용사.",
            "body": [
                "한국어를 막 시작했든, 여행이나 TOPIK, 일상 회화를 위해 복습하든, 단어 공부를 짧고 꾸준한 습관으로 만들어 줍니다.",
                "명사, 동사, 형용사 각 1,500개를 10문제씩 짧게 풀고, 원어민 발음을 듣고, 틀린 단어는 자동으로 모아 복습할 수 있습니다.",
            ],
            "features": ["필수 단어 4,500개", "한국어 → 영어, 영어 → 한국어 문제", "원어민 발음(TTS)",
                         "오답과 학습한 단어 복습", "계정 없이, 오프라인에서도 학습"],
        },
    },
    {
        "slug": "learn-korean-hangul",
        "package": "com.kysystemstudio.learnkorean",
        "kind": "learning",
        "new": False,
        "icon": "https://play-lh.googleusercontent.com/zMJ0vnl5zQoDtV_pIpN-GNOc-t8LlfgGgNXo8uX6yzVLtIzQ6pp8fEJQIgJ-j2gQB0_-iayqivpCyCNAkbUziw",
        "shots_key": "learnkorean",
        "youtube": None,
        "en": {
            "name": "Learn Korean – Hangul",
            "short": "Learn the Korean alphabet with audio pronunciation and stroke order.",
            "body": [
                "The perfect start for absolute beginners: learn the Korean alphabet, Hangul, from scratch.",
                "Go through 14 consonants, 5 double consonants, 10 vowels, 11 compound vowels and 30 essential words, each with audio pronunciation and stroke order practice.",
            ],
            "features": ["Audio for every letter and word", "Stroke order practice", "Clean, easy interface",
                         "No login required", "Completely free"],
        },
        "ko": {
            "name": "Learn Korean – Hangul",
            "short": "음성 발음과 획순으로 한국어 알파벳, 한글을 배워 보세요.",
            "body": [
                "한국어를 처음 배우는 분이 한글을 기초부터 익힐 수 있는 앱입니다.",
                "자음 14개, 쌍자음 5개, 모음 10개, 복합모음 11개, 기본 단어 30개를 발음 듣기와 획순 연습으로 배웁니다.",
            ],
            "features": ["모든 글자와 단어의 발음", "획순 연습", "깔끔하고 쉬운 화면", "로그인 필요 없음", "완전 무료"],
        },
    },
    {
        "slug": "world-history-quiz",
        "package": "com.kysystemstudio.historychallenge",
        "kind": "learning",
        "new": False,
        "icon": "https://play-lh.googleusercontent.com/4y95jsn1q0i6blLn5Dk-H2jnbJ_n-1V7V1mrfWJrduzq3dWT7K3MxvRskUD0NPoNsmoO1qqLaNXRSWxTxwjz",
        "shots_key": "historychallenge",
        "youtube": None,
        "en": {
            "name": "World History Quiz",
            "short": "Test your world history knowledge through fun quizzes.",
            "body": [
                "How well do you know world history? A multiple-choice quiz game that helps you learn and review history in a fun, engaging way.",
                "Choose from five eras and three quiz types, and work through six stages that get harder as you go. Your progress is saved automatically.",
            ],
            "features": ["5 eras: Ancient to Contemporary", "3 quiz types: Person, Year and Event",
                         "6 stages of rising difficulty", "10 questions per session", "English and Korean"],
        },
        "ko": {
            "name": "World History Quiz",
            "short": "재미있는 퀴즈로 세계사 지식을 시험해 보세요.",
            "body": [
                "세계사를 얼마나 알고 있나요? 객관식 퀴즈로 세계사를 재미있게 배우고 복습할 수 있는 게임입니다.",
                "다섯 시대와 세 가지 퀴즈 유형 중에서 고르고, 점점 어려워지는 여섯 단계를 풀어 보세요. 진행 상황은 자동으로 저장됩니다.",
            ],
            "features": ["고대부터 현대까지 5개 시대", "인물, 연도, 사건 3가지 유형", "점점 어려워지는 6단계",
                         "한 번에 10문제", "영어와 한국어 지원"],
        },
    },
]

# Newest first. Set "draft": True to keep an entry off the site until it's true.
NEWS = [
    {
        "date": "2026-10-05",
        "game": None,
        "en": {"title": "Our new website",
               "body": "All our games now have their own pages here, in English and Korean, along with news, support and the studio story."},
        "ko": {"title": "새 홈페이지를 열었습니다",
               "body": "모든 게임의 소개 페이지와 소식, 지원, 스튜디오 이야기를 영어와 한국어로 한곳에 모았습니다."},
    },
    {
        "date": "2026-10-05",
        "game": "hilltop-roll",
        "en": {"title": "Hilltop Roll 1.0.1: music and sound",
               "body": "Hilltop Roll now has music and sound effects: whooshes, touchdowns, rising chimes for perfect combos and more. Turn music and sound on or off separately in Settings."},
        "ko": {"title": "Hilltop Roll 1.0.1: 음악과 효과음 추가",
               "body": "Hilltop Roll에 음악과 효과음이 생겼습니다. 점프, 착지, 콤보마다 높아지는 PERFECT 소리 등을 들어 보세요. 설정에서 음악과 효과음을 따로 켜고 끌 수 있습니다."},
    },
    {
        "date": "2026-09-25",
        "game": "hilltop-roll",
        "en": {"title": "Hilltop Roll is out on Google Play",
               "body": "Our new one-finger rolling game is here. Hold to race down the hills, lift your finger to fly over the gaps, and see how far you can roll."},
        "ko": {"title": "Hilltop Roll 출시",
               "body": "한 손가락으로 즐기는 새 공 굴리기 게임이 나왔습니다. 누르고 언덕을 내려가다 손을 떼서 구멍을 넘어 보세요. 얼마나 멀리 갈 수 있을까요?"},
    },
]

ABOUT = {
    "en": [
        "ggook's studio is a small independent studio in Seoul, Korea.",
        "We make simple, friendly mobile games and learning apps: the kind you can pick up in a minute, understand without a tutorial and come back to every day. Some are quick arcade games like Hilltop Roll and Updraft; others help you learn, like our Korean and world history quizzes.",
        "Our games are free to play and supported by ads. We keep things light: no accounts, no sign-ups, and your progress stays on your device.",
        "Thanks for playing. If you have an idea or find a bug, we'd love to hear from you.",
    ],
    "ko": [
        "ggook's studio는 서울에 있는 작은 독립 스튜디오입니다.",
        "잠깐이면 시작할 수 있고, 설명 없이도 이해되고, 매일 다시 찾게 되는 간단하고 친근한 모바일 게임과 학습 앱을 만듭니다. Hilltop Roll, Updraft 같은 짧은 아케이드 게임도 있고, 한국어와 세계사 퀴즈처럼 배움을 돕는 앱도 있습니다.",
        "모든 게임은 광고로 운영되는 무료 게임입니다. 계정이나 가입 없이 바로 즐길 수 있고, 기록은 기기에만 저장됩니다.",
        "플레이해 주셔서 감사합니다. 아이디어나 버그가 있다면 언제든 알려 주세요.",
    ],
}

FAQ = {
    "en": [
        ("Do I need an account?",
         "No. None of our games need an account or sign-up. Your scores and progress are saved only on your device."),
        ("How do I delete my data?",
         "Our games don't collect personal information on our servers. Your progress is stored on your device, so uninstalling the app (or clearing its data in Android settings) deletes it. Ads are served by Google AdMob; you can reset or delete your advertising ID in your device's Google settings. If you have any other request, email us."),
        ("Why are there ads?",
         "Ads keep our games free. Some games also offer optional rewarded ads, for example to continue a run or get a hint, which you only watch if you choose to."),
        ("How do I change my ad consent (privacy settings)?",
         "If you're in a region that requires consent, such as the EEA or the UK, a consent form appears on first launch. In Hilltop Roll you can change your choice later in Settings > Privacy settings. For our other apps, email us and we'll help."),
        ("How do I reset my best score?",
         "In Hilltop Roll, open Settings (the gear button) and tap Reset best score twice."),
        ("I found a bug. What should I send?",
         "Email us the game name, your phone model, the app version (shown in Settings) and what happened. A screenshot helps a lot."),
    ],
    "ko": [
        ("계정이 필요한가요?",
         "아니요. 모든 게임은 계정이나 가입 없이 즐길 수 있습니다. 점수와 진행 상황은 기기에만 저장됩니다."),
        ("내 데이터를 삭제하려면 어떻게 하나요?",
         "저희 게임은 서버에 개인정보를 수집하지 않습니다. 진행 상황은 기기에 저장되므로 앱을 삭제하거나 Android 설정에서 앱 데이터를 지우면 함께 삭제됩니다. 광고는 Google AdMob이 제공하며, 기기의 Google 설정에서 광고 ID를 재설정하거나 삭제할 수 있습니다. 그 밖의 요청은 이메일로 보내 주세요."),
        ("왜 광고가 나오나요?",
         "광고 덕분에 게임을 무료로 제공할 수 있습니다. 일부 게임은 이어하기나 힌트처럼 원할 때만 보는 보상형 광고도 제공합니다."),
        ("광고 동의(개인정보 설정)를 바꾸려면?",
         "유럽(EEA), 영국 등 동의가 필요한 지역에서는 처음 실행할 때 동의 창이 나옵니다. Hilltop Roll은 설정 > 개인정보 설정(Privacy settings)에서 나중에 바꿀 수 있습니다. 다른 앱은 이메일로 문의해 주세요."),
        ("최고 기록을 초기화하려면?",
         "Hilltop Roll에서 설정(톱니바퀴 버튼)을 열고 '최고 기록 초기화'를 두 번 누르세요."),
        ("버그를 발견했어요. 무엇을 보내면 되나요?",
         "게임 이름, 휴대폰 기종, 앱 버전(설정에 표시), 어떤 일이 있었는지를 이메일로 보내 주세요. 스크린샷이 있으면 큰 도움이 됩니다."),
    ],
}
